CREATE TABLE fleet (
    id INT PRIMARY KEY AUTO_INCREMENT,
    vehicle_number VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO fleet (vehicle_number, vehicle_type) VALUES ('AG0001DB', 'BUS'), ('AG0002DB', 'TRUCK'), ('AG0003DB', 'CAR');