-- INIT H2 DATABASE SCHEMA
CREATE TABLE fleet (
    id INT PRIMARY KEY AUTO_INCREMENT,
    vehicle_number VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE fleet_location (
    id INT PRIMARY KEY AUTO_INCREMENT,
    fleet_id INTEGER,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fleet FOREIGN KEY (fleet_id) REFERENCES fleet(id) ON DELETE CASCADE
);